set_pin_physical_constraints -pin_name {gclk} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 107


set_pin_physical_constraints -pin_name {const_cpuid[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 1
set_pin_physical_constraints -pin_name {const_cpuid[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 2
set_pin_physical_constraints -pin_name {tcu_shscanid[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 3
set_pin_physical_constraints -pin_name {tcu_shscanid[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 4
set_pin_physical_constraints -pin_name {tcu_shscanid[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 5
set_pin_physical_constraints -pin_name {scan_out[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 6
set_pin_physical_constraints -pin_name {scan_out[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 7
set_pin_physical_constraints -pin_name {scan_in[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 8
set_pin_physical_constraints -pin_name {scan_in[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 9
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[4]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 10
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[3]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 11
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 12
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 13
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 14
set_pin_physical_constraints -pin_name {dmo_dout[35]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 15
set_pin_physical_constraints -pin_name {dmo_dout[34]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 16
set_pin_physical_constraints -pin_name {dmo_dout[33]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 17
set_pin_physical_constraints -pin_name {dmo_dout[32]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 18
set_pin_physical_constraints -pin_name {dmo_dout[31]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 19
set_pin_physical_constraints -pin_name {dmo_dout[30]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 20
set_pin_physical_constraints -pin_name {dmo_dout[29]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 21
set_pin_physical_constraints -pin_name {dmo_dout[28]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 22
set_pin_physical_constraints -pin_name {dmo_dout[27]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 23
set_pin_physical_constraints -pin_name {dmo_dout[26]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 24
set_pin_physical_constraints -pin_name {dmo_dout[25]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 25
set_pin_physical_constraints -pin_name {dmo_dout[24]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 26
set_pin_physical_constraints -pin_name {dmo_dout[23]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 27
set_pin_physical_constraints -pin_name {dmo_dout[22]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 28
set_pin_physical_constraints -pin_name {dmo_dout[21]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 29
set_pin_physical_constraints -pin_name {dmo_dout[20]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 30
set_pin_physical_constraints -pin_name {dmo_dout[19]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 31
set_pin_physical_constraints -pin_name {dmo_dout[18]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 32
set_pin_physical_constraints -pin_name {dmo_dout[17]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 33
set_pin_physical_constraints -pin_name {dmo_dout[16]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 34
set_pin_physical_constraints -pin_name {dmo_dout[15]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 35
set_pin_physical_constraints -pin_name {dmo_dout[14]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 36
set_pin_physical_constraints -pin_name {dmo_dout[13]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 37
set_pin_physical_constraints -pin_name {dmo_dout[12]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 38
set_pin_physical_constraints -pin_name {dmo_dout[11]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 39
set_pin_physical_constraints -pin_name {dmo_dout[10]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 40
set_pin_physical_constraints -pin_name {dmo_dout[9]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 41
set_pin_physical_constraints -pin_name {dmo_dout[8]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 42
set_pin_physical_constraints -pin_name {dmo_dout[7]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 43
set_pin_physical_constraints -pin_name {dmo_dout[6]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 44
set_pin_physical_constraints -pin_name {dmo_dout[5]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 45
set_pin_physical_constraints -pin_name {dmo_dout[4]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 46
set_pin_physical_constraints -pin_name {dmo_dout[3]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 47
set_pin_physical_constraints -pin_name {dmo_dout[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 48
set_pin_physical_constraints -pin_name {dmo_dout[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 49
set_pin_physical_constraints -pin_name {dmo_dout[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 50
set_pin_physical_constraints -pin_name {dmo_din[35]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 51
set_pin_physical_constraints -pin_name {dmo_din[34]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 52
set_pin_physical_constraints -pin_name {dmo_din[33]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 53
set_pin_physical_constraints -pin_name {dmo_din[32]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 54
set_pin_physical_constraints -pin_name {dmo_din[31]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 55
set_pin_physical_constraints -pin_name {dmo_din[30]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 56
set_pin_physical_constraints -pin_name {dmo_din[29]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 57
set_pin_physical_constraints -pin_name {dmo_din[28]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 58
set_pin_physical_constraints -pin_name {dmo_din[27]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 59
set_pin_physical_constraints -pin_name {dmo_din[26]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 60
set_pin_physical_constraints -pin_name {dmo_din[25]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 61
set_pin_physical_constraints -pin_name {dmo_din[24]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 62
set_pin_physical_constraints -pin_name {dmo_din[23]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 63
set_pin_physical_constraints -pin_name {dmo_din[22]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 64
set_pin_physical_constraints -pin_name {dmo_din[21]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 65
set_pin_physical_constraints -pin_name {dmo_din[20]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 66
set_pin_physical_constraints -pin_name {dmo_din[19]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 67
set_pin_physical_constraints -pin_name {dmo_din[18]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 68
set_pin_physical_constraints -pin_name {dmo_din[17]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 69
set_pin_physical_constraints -pin_name {dmo_din[16]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 70
set_pin_physical_constraints -pin_name {dmo_din[15]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 71
set_pin_physical_constraints -pin_name {dmo_din[14]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 72
set_pin_physical_constraints -pin_name {dmo_din[13]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 73
set_pin_physical_constraints -pin_name {dmo_din[12]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 74
set_pin_physical_constraints -pin_name {dmo_din[11]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 75
set_pin_physical_constraints -pin_name {dmo_din[10]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 76
set_pin_physical_constraints -pin_name {dmo_din[9]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 77
set_pin_physical_constraints -pin_name {dmo_din[8]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 78
set_pin_physical_constraints -pin_name {dmo_din[7]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 79
set_pin_physical_constraints -pin_name {dmo_din[6]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 80
set_pin_physical_constraints -pin_name {dmo_din[5]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 81
set_pin_physical_constraints -pin_name {dmo_din[4]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 82
set_pin_physical_constraints -pin_name {dmo_din[3]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 83
set_pin_physical_constraints -pin_name {dmo_din[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 84
set_pin_physical_constraints -pin_name {dmo_din[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 85
set_pin_physical_constraints -pin_name {dmo_din[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 86
set_pin_physical_constraints -pin_name {const_cpuid[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 87
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[82]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 88
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[81]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 89
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[80]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 90
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[79]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 91
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[78]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 92
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[77]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 93
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[76]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 94
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[75]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 95
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[74]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 96
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[73]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 97
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[72]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 98
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[71]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 99
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[70]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 100
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[69]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 101
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[68]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 102
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[67]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 103
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[66]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 104
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[65]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 105
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[64]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 106
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[63]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 107
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[62]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 108
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[61]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 109
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[60]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 110
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[59]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 111
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[58]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 112
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[57]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 113
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[56]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 114
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[55]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 115
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[54]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 116
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[53]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 117
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[52]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 118
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[51]} -layers {metal3} -width 0.05 -depth 0.05 -side 1 -order 119
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[87]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 1
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[86]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 2
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[85]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 3
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[84]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 4
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[83]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 5
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[65]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 6
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[64]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 7
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[63]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 8
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[62]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 9
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[61]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 10
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[60]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 11
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[59]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 12
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[58]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 13
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[57]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 14
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[56]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 15
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[55]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 16
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[54]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 17
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[53]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 18
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[52]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 19
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[51]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 20
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[50]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 21
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[49]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 22
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[48]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 23
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[47]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 24
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[46]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 25
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[45]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 26
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[44]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 27
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[43]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 28
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[42]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 29
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[41]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 30
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[40]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 31
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[39]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 32
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[38]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 33
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[37]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 34
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[36]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 35
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[35]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 36
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[34]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 37
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[33]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 38
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[32]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 39
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[31]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 40
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[30]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 41
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[29]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 42
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[28]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 43
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[27]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 44
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[26]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 45
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[25]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 46
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[24]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 47
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[23]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 48
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[22]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 49
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[21]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 50
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[20]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 51
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[19]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 52
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[18]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 53
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[17]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 54
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[16]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 55
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[15]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 56
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[14]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 57
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[13]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 58
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[12]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 59
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[11]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 60
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[10]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 61
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[9]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 62
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[8]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 63
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[7]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 64
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[6]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 65
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[5]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 66
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[4]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 67
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[3]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 68
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 69
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 70
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 71
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[8]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 72
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[7]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 73
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[6]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 74
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[5]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 75
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[4]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 76
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[3]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 77
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 78
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 79
set_pin_physical_constraints -pin_name {spc_pcx_atm_pq[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 80
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[8]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 81
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[7]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 82
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[6]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 83
set_pin_physical_constraints -pin_name {spc_core_running_status[5]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 84
set_pin_physical_constraints -pin_name {spc_core_running_status[4]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 85
set_pin_physical_constraints -pin_name {spc_core_running_status[3]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 86
set_pin_physical_constraints -pin_name {spc_core_running_status[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 87
set_pin_physical_constraints -pin_name {spc_core_running_status[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 88
set_pin_physical_constraints -pin_name {spc_core_running_status[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 89
set_pin_physical_constraints -pin_name {tcu_core_running[7]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 90
set_pin_physical_constraints -pin_name {tcu_core_running[6]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 91
set_pin_physical_constraints -pin_name {tcu_core_running[5]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 92
set_pin_physical_constraints -pin_name {tcu_core_running[4]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 93
set_pin_physical_constraints -pin_name {tcu_core_running[3]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 94
set_pin_physical_constraints -pin_name {tcu_core_running[2]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 95
set_pin_physical_constraints -pin_name {tcu_core_running[1]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 96
set_pin_physical_constraints -pin_name {tcu_core_running[0]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 97
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[129]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 98
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[128]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 99
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[127]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 100
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[126]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 101
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[125]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 102
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[124]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 103
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[123]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 104
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[122]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 105
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[121]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 106
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[120]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 107
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[119]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 108
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[118]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 109
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[117]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 110
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[116]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 111
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[115]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 112
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[114]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 113
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[113]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 114
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[112]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 115
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[111]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 116
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[110]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 117
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[109]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 118
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[108]} -layers {metal3} -width 0.05 -depth 0.05 -side 3 -order 119
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[50]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 1
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[49]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 2
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[48]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 3
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[47]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 4
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[46]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 5
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[45]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 6
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[44]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 7
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[43]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 8
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[42]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 9
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[41]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 10
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[40]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 11
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[39]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 12
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[38]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 13
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[37]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 14
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[36]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 15
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[35]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 16
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[34]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 17
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[33]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 18
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[32]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 19
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[31]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 20
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[30]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 21
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[29]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 22
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[28]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 23
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[27]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 24
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[26]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 25
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[25]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 26
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[24]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 27
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[23]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 28
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[22]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 29
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[21]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 30
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[20]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 31
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[19]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 32
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[18]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 33
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[17]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 34
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[16]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 35
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[15]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 36
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[14]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 37
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[13]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 38
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[12]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 39
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[11]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 40
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[10]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 41
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[9]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 42
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[8]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 43
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[7]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 44
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[6]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 45
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[5]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 46
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[5]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 47
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[4]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 48
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[3]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 49
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[2]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 50
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[1]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 51
set_pin_physical_constraints -pin_name {spc_pcx_req_pq[0]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 52
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[8]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 53
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[7]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 54
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[6]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 55
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[5]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 56
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[4]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 57
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[3]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 58
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[2]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 59
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[1]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 60
set_pin_physical_constraints -pin_name {spc_core_running_status[6]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 61
set_pin_physical_constraints -pin_name {pcx_spc_grant_px[0]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 62
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[145]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 63
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[144]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 64
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[143]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 65
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[142]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 66
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[141]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 67
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[140]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 68
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[139]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 69
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[138]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 70
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[137]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 71
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[136]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 72
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[135]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 73
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[134]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 74
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[133]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 75
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[132]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 76
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[131]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 77
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[130]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 78
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[129]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 79
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[128]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 80
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[127]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 81
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[126]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 82
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[125]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 83
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[124]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 84
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[123]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 85
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[122]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 86
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[121]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 87
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[120]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 88
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[119]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 89
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[118]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 90
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[117]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 91
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[116]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 92
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[115]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 93
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[114]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 94
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[113]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 95
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[112]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 96
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[111]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 97
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[110]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 98
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[109]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 99
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[108]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 100
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[107]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 101
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[106]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 102
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[105]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 103
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[104]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 104
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[103]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 105
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[102]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 106
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[101]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 107
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[100]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 108
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[99]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 109
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[98]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 110
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[97]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 111
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[96]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 112
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[95]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 113
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[94]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 114
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[93]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 115
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[92]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 116
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[91]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 117
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[90]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 118
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[89]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 119
set_pin_physical_constraints -pin_name {cpx_spc_data_cx[88]} -layers {metal2} -width 0.05 -depth 0.05 -side 2 -order 120
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[107]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 1
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[106]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 2
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[105]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 3
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[104]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 4
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[103]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 5
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[102]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 6
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[101]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 7
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[100]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 8
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[99]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 9
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[98]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 10
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[97]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 11
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[96]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 12
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[95]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 13
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[94]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 14
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[93]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 15
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[92]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 16
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[91]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 17
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[90]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 18
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[89]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 19
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[88]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 20
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[87]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 21
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[86]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 22
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[85]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 23
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[84]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 24
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[83]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 25
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[82]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 26
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[81]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 27
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[80]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 28
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[79]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 29
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[78]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 30
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[77]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 31
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[76]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 32
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[75]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 33
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[74]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 34
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[73]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 35
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[72]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 36
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[71]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 37
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[70]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 38
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[69]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 39
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[68]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 40
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[67]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 41
set_pin_physical_constraints -pin_name {spc_pcx_data_pa[66]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 42
set_pin_physical_constraints -pin_name {spc_tcu_lbist_scan_out} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 43
set_pin_physical_constraints -pin_name {spc_tcu_lbist_done} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 44
set_pin_physical_constraints -pin_name {spc_efu_fuse_dxfer_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 45
set_pin_physical_constraints -pin_name {spc_efu_fuse_ixfer_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 46
set_pin_physical_constraints -pin_name {spc_efu_fuse_idata} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 47
set_pin_physical_constraints -pin_name {spc_efu_fuse_ddata} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 48
set_pin_physical_constraints -pin_name {spc_trigger_pulse} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 49
set_pin_physical_constraints -pin_name {spc_softstop_request} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 50
set_pin_physical_constraints -pin_name {spc_hardstop_request} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 51
set_pin_physical_constraints -pin_name {spc_ss_complete} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 52
set_pin_physical_constraints -pin_name {spc_tcu_mbist_scan_out} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 53
set_pin_physical_constraints -pin_name {spc_mbist_done} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 54
set_pin_physical_constraints -pin_name {spc_mbist_fail} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 55
set_pin_physical_constraints -pin_name {spc_shscan_scan_out} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 56
set_pin_physical_constraints -pin_name {ccu_cmp_slow_sync_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 57
set_pin_physical_constraints -pin_name {ccu_slow_cmp_sync_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 58
set_pin_physical_constraints -pin_name {ncu_spc_l2_idx_hash_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 59
set_pin_physical_constraints -pin_name {dmo_dcmuxctl} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 60
set_pin_physical_constraints -pin_name {dmo_icmuxctl} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 61
set_pin_physical_constraints -pin_name {dmo_coresel} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 62
set_pin_physical_constraints -pin_name {tcu_spc_test_mode} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 63
set_pin_physical_constraints -pin_name {tcu_spc_lbist_pgm} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 64
set_pin_physical_constraints -pin_name {tcu_spc_lbist_scan_in} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 65
set_pin_physical_constraints -pin_name {tcu_spc_lbist_start} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 66
set_pin_physical_constraints -pin_name {vnw_ary1} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 67
set_pin_physical_constraints -pin_name {vnw_ary0} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 68
set_pin_physical_constraints -pin_name {efu_spc_fuse_dclr} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 69
set_pin_physical_constraints -pin_name {efu_spc_fuse_iclr} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 70
set_pin_physical_constraints -pin_name {efu_spc_fuse_dxfer_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 71
set_pin_physical_constraints -pin_name {efu_spc_fuse_ixfer_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 72
set_pin_physical_constraints -pin_name {efu_spc_fuse_data} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 73
set_pin_physical_constraints -pin_name {ncu_spc_ba67} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 74
set_pin_physical_constraints -pin_name {ncu_spc_ba45} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 75
set_pin_physical_constraints -pin_name {ncu_spc_ba23} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 76
set_pin_physical_constraints -pin_name {ncu_spc_ba01} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 77
set_pin_physical_constraints -pin_name {ncu_spc_pm} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 78
set_pin_physical_constraints -pin_name {ncu_wmr_vec_mask} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 79
set_pin_physical_constraints -pin_name {ncu_cmp_tick_enable} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 80
set_pin_physical_constraints -pin_name {tcu_ss_request} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 81
set_pin_physical_constraints -pin_name {tcu_do_mode} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 82
set_pin_physical_constraints -pin_name {tcu_ss_mode} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 83
set_pin_physical_constraints -pin_name {tcu_mbist_user_mode} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 84
set_pin_physical_constraints -pin_name {tcu_spc_mbist_start} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 85
set_pin_physical_constraints -pin_name {tcu_mbist_bisi_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 86
set_pin_physical_constraints -pin_name {tcu_spc_mbist_scan_in} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 87
set_pin_physical_constraints -pin_name {cluster_arst_l} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 88
set_pin_physical_constraints -pin_name {tcu_shscan_scan_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 89
set_pin_physical_constraints -pin_name {tcu_shscan_scan_in} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 90
set_pin_physical_constraints -pin_name {tcu_shscan_bclk} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 91
set_pin_physical_constraints -pin_name {tcu_shscan_aclk} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 92
set_pin_physical_constraints -pin_name {tcu_shscan_clk_stop} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 93
set_pin_physical_constraints -pin_name {tcu_shscan_pce_ov} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 94
set_pin_physical_constraints -pin_name {rst_wmr_protect} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 95
set_pin_physical_constraints -pin_name {tcu_atpg_mode} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 96
set_pin_physical_constraints -pin_name {tcu_se_scancollar_out} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 97
set_pin_physical_constraints -pin_name {tcu_se_scancollar_in} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 98
set_pin_physical_constraints -pin_name {tcu_array_wr_inhibit} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 99
set_pin_physical_constraints -pin_name {tcu_scan_en} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 100
set_pin_physical_constraints -pin_name {tcu_muxtest} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 101
set_pin_physical_constraints -pin_name {tcu_dectest} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 102
set_pin_physical_constraints -pin_name {tcu_bclk} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 103
set_pin_physical_constraints -pin_name {tcu_aclk} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 104
set_pin_physical_constraints -pin_name {tcu_clk_stop} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 105
set_pin_physical_constraints -pin_name {tcu_pce_ov} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 106
set_pin_physical_constraints -pin_name {hver_mask_minor_rev[3]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 108
set_pin_physical_constraints -pin_name {hver_mask_minor_rev[2]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 109
set_pin_physical_constraints -pin_name {hver_mask_minor_rev[1]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 110
set_pin_physical_constraints -pin_name {hver_mask_minor_rev[0]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 111
set_pin_physical_constraints -pin_name {spc_dbg_instr_cmt_grp1[1]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 112
set_pin_physical_constraints -pin_name {spc_dbg_instr_cmt_grp1[0]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 113
set_pin_physical_constraints -pin_name {spc_dbg_instr_cmt_grp0[1]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 114
set_pin_physical_constraints -pin_name {spc_dbg_instr_cmt_grp0[0]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 115
set_pin_physical_constraints -pin_name {power_throttle[2]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 116
set_pin_physical_constraints -pin_name {power_throttle[1]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 117
set_pin_physical_constraints -pin_name {power_throttle[0]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 118
set_pin_physical_constraints -pin_name {spc_core_running_status[7]} -layers {metal2} -width 0.05 -depth 0.05 -side 4 -order 119
