set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 843.0200 -nets VDD -layer 17 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 3.0650 -nets VDD -layer 17 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 3.0650 -nets VDD -layer 19 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1326.6350 -nets VDD -layer 19 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 841.0900 -nets VSS -layer 17 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 4.9950 -nets VSS -layer 17 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 5.0950 -nets VSS -layer 19 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1324.6050 -nets VSS -layer 19 -width 1.1300 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 45.0050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.8050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 124.6050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 164.3050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 204.1050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 243.9050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 283.7050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 323.5050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 363.2050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 403.0050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 442.8050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 482.6050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 522.4050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 562.1050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 601.9050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 641.7050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 681.5050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 721.3050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 761.0050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 800.8050 -nets VDD  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 45.1950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.9950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 124.7950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 164.4950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 204.2950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 244.0950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 283.8950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 323.6950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 363.3950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 403.1950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 442.9950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 482.7950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 522.5950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 562.2950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 602.0950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 641.8950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 681.6950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 721.4950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 761.1950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 800.9950 -nets VSS  -layer 13 -width 0.1000 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 67.9750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 130.7750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 193.6750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 256.4750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 319.2750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 382.0750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 444.8750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 507.6750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 570.4750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 633.2750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 696.0750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 758.8750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 821.7750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 884.5750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 947.3750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1010.1750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1072.9750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1135.7750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1198.5750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1261.3750 -nets VDD  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 68.2250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 131.0250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 193.9250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 256.7250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 319.5250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 382.3250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 445.1250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 507.9250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 570.7250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 633.5250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 696.3250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 759.1250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 822.0250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 884.8250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 947.6250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1010.4250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1073.2250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1136.0250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1198.8250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1261.6250 -nets VSS  -layer 15 -width 0.1100 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 44.2775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.2775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 124.2775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 164.2775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 203.4775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 243.4775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 283.4775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 322.6775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 362.6775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 402.6775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 442.6775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 481.8775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 521.8775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 561.8775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 601.8775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 641.0775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 681.0775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 721.0775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 760.2775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 800.2775 -nets VDD  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 1327.2000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 45.3225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 85.3225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 125.3225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 165.3225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 204.5225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 244.5225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 284.5225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 323.7225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 363.7225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 403.7225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 443.7225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 482.9225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 522.9225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 562.9225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 602.9225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 642.1225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 682.1225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 722.1225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 761.3225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 801.3225 -nets VSS  -layer 17 -width 0.5650 -pitch_within_group 39.780 -start_low_ends coordinate  -start_low_ends_coordinate 4.5300 -start_high_ends coordinate  -start_high_ends_coordinate 1325.1700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 67.2675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 130.4675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 192.8675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 256.0675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 318.4675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 381.6675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 444.0675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 507.2675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 569.6675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 632.8675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 695.2675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 758.4675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 820.8675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 884.0675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 946.4675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1009.6675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1072.0675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1135.2675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1197.6675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1260.8675 -nets VDD  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 2.5000 -start_high_ends coordinate  -start_high_ends_coordinate 843.5850 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 68.7325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 131.9325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 194.3325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 257.5325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 319.9325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 383.1325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 445.5325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 508.7325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 571.1325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 634.3325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 696.7325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 759.9325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 822.3325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 885.5325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 947.9325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1011.1325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1073.5325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1136.7325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1199.1325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1262.3325 -nets VSS  -layer 19 -width 0.5650 -pitch_within_group 62.810 -start_low_ends coordinate  -start_low_ends_coordinate 4.4300 -start_high_ends coordinate  -start_high_ends_coordinate 841.6550 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
